/// FOR SERVICES PAGE
export const SERVICES_FETCH_DATA_SUCCESS = "SERVICES_FETCH_DATA_SUCCESS";
export const ADD_SERVICE = "ADD_SERVICE";
export const EDIT_SERVICE = "EDIT_SERVICE";
export const DELETE_SERVICE = "DELETE_SERVICE";
/// FOR APPOINTMENTS PAGE
export const APPOINTMENTS_FETCH_DATA_SUCCESS = "APPOINTMENTS_FETCH_DATA_SUCCESS";
export const ADD_APPOINTMENT = "ADD_APPOINTMENT";
export const EDIT_APPOINTMENT = "EDIT_APPOINTMENT";
export const DELETE_APPOINTMENT = "DELETE_APPOINTMENT";